* DESCOMPONER LA CADENA CON EL NOMBRE DEL COLEGIO
CLEAR
CADENA = "UNIDAD EDUCATIVA MANUELA GARAICOA DE CALDERON"
* 1
P=SUBSTR(CADENA,1,AT(" ",CADENA,1)-1)
?p
* 2
s=SUBSTR(CADENA,AT(" ",CADENA,1)+1,AT(" ",CADENA,2)-AT(" ",CADENA,1))
?s
* 3
t=SUBSTR(CADENA,AT(" ",CADENA,2)+1,AT(" ",CADENA,3)-AT(" ",CADENA,2))
?t
* 4
c=SUBSTR(CADENA,AT(" ",CADENA,3)+1,AT(" ",CADENA,4)-AT(" ",CADENA,3))
?c
* 5
q=SUBSTR(CADENA,AT(" ",CADENA,4)+1,AT(" ",CADENA,5))
?q